export let quiz = [
  {
    id: 1,
    type: "short_answer",
    question: "what is your name?",
    answers: [],
    correct_answer: 0,
  },
  {
    id: 2,
    type: "long_text",
    question:
      "so, first things first, how do you catchup with nellie and co , content?",
    answers: [],
    correct_answer: 0,
  },
  {
    id: 3,
    type: "multiple_choice",
    question: "What industry are you in?",
    answers: [
      { id: 1, answer: "Professinal services" },
      { id: 2, answer: "Agency (advertising, marketing, design)" },
      { id: 3, answer: "Health care" },
      { id: 4, answer: "Consumer Apps and Media" },
      { id: 5, answer: "Consumer Services" },
      { id: 6, answer: "Software and services" },
      { id: 7, answer: "E-Commerce, Retail, and Consumer goods" },
      { id: 8, answer: "Education" },
      { id: 8, answer: "Other" },
    ],
    correct_answer: 1,
  },
  {
    id: 4,
    type: "multiple_selection_choice",
    question: "Choose as many as you like",
    answers: [
      { value: "One", label: "One" },
      { value: "Two", label: "Two" },
      { value: "Three", label: "Three" },
      { value: "Four", label: "Four" },
    ],
    correct_answer: 1,
  },
  //   {
  //     id: 5,
  //     type: "description",
  //     question: "random text to show to the user",
  //     answers: [],
  //     correct_answer: 0,
  //   },
  //   {
  //     id: 6,
  //     type: "true_false",
  //     question: "Is the sky blue",
  //     answers: [],
  //     correct_answer: 2,
  //   },
];
